version: '3'
services:
  db:
    extends:
      file: ../api/docker-compose.yml
      service: db
  redis:
    extends:
      file: ../api/docker-compose.yml
      service: redis 
  api:
    extends:
      file: ../api/docker-compose.yml
      service: api
    depends_on:
     - db
  web:
    extends:
      file: ../web/docker-compose.yml
      service: web
    depends_on:
     - api

  gateway:
    build: ./gateway/
    ports:
      - "80:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
     - api
     - web



